### ISSUE TITLE
Add GCE terraform/ansible support

### ISSUE THREAD

**Issue by rimusz** [dcos-labs/terraform-ansible-dcos#1]

**Comment by jrx** [comment]
I'm actually think of getting the Terraform parts replaced by @bernadinm scripts: https://github.com/dcos/terraform-dcos

So we could use his terraform core plus the Ansible scripts and don't need do the infrastructure work again. 

@bernadinm Do you have any thoughts on this?

**Comment by rimusz** [comment]
nice project @bernadinm https://github.com/bernadinm/terraform-dcos 👍 
@jrx that sounds as a good idea, separating infra from the dc/os install

**Comment by adyatlov** [comment]
https://github.com/bernadinm/terraform-dcos doesn't have GCP support yet.

**Comment by rimusz** [comment]
@adyatlov  that's the one https://github.com/dcos/terraform-dcos

**Comment by rimusz** [comment]
Terraform part is working fine.
ansible playbook does not properly setup DC/OS yet

**Comment by rimusz** [comment]
implemented
