### ISSUE TITLE
`terraform init -from-module ...` overwrites main README.md

### ISSUE THREAD

**Issue by rimusz** [dcos-labs/terraform-ansible-dcos#4]
`terraform init -from-module github.com/jrx/terraform-dcos//aws/gcp` overwrites main `README.md` with the file from `github.com/jrx/terraform-dcos`

**Comment by jrx** [comment]
This is fixed. The `README.md` will not get overwritten anymore. The `terraform init ..` will be done a sub folder called `.deploy`.
